<?xml version="1.0" encoding="UTF-8"?>
<bajadoc version="2.0" createdBy="niagara-baja-doclet-1.0.9" createdAt="03-May-2024" createdOn="883e7f7a9875">
<class module="history" runtimeProfile="rt" qualifiedName="javax.baja.history.HistoryClosedException" name="HistoryClosedException" packageName="javax.baja.history" public="true" category="exception">
<description>
HistoryClosedException is thrown when a history is closed at a time&#xa; when it is expected to be open.
</description>
<tag name="@author">John Sublett</tag>
<tag name="@creation">18 Jul 2002</tag>
<tag name="@version">$Revision: 1$ $Date: 7/26/02 3:52:23 PM EDT$</tag>
<tag name="@since">Baja 1.0</tag>
<extends>
<type class="javax.baja.history.HistoryException"/>
</extends>
<!-- javax.baja.history.HistoryClosedException(java.lang.String) -->
<constructor name="HistoryClosedException" public="true">
<parameter name="msg">
<type class="java.lang.String"/>
</parameter>
<description>
Construct a HistoryException with the given message.
</description>
</constructor>

<!-- javax.baja.history.HistoryClosedException() -->
<constructor name="HistoryClosedException" public="true">
<description>
No argument constructor.
</description>
</constructor>

</class>
</bajadoc>
