<?xml version="1.0" encoding="UTF-8"?>
<bajadoc version="2.0" createdBy="niagara-baja-doclet-1.0.9" createdAt="03-May-2024" createdOn="883e7f7a9875">
<class module="history" runtimeProfile="rt" qualifiedName="javax.baja.history.HistoryNameException" name="HistoryNameException" packageName="javax.baja.history" public="true" category="exception">
<description>
A HistoryNameException is thrown when an attempt is made to&#xa; create a history with an invalid name.
</description>
<tag name="@author">John Sublett</tag>
<tag name="@creation">16 Mar 2005</tag>
<tag name="@version">$Revision: 1$ $Date: 3/17/05 5:19:19 PM EST$</tag>
<tag name="@since">Baja 1.0</tag>
<extends>
<type class="javax.baja.history.HistoryException"/>
</extends>
<!-- javax.baja.history.HistoryNameException() -->
<constructor name="HistoryNameException" public="true">
<description/>
</constructor>

<!-- javax.baja.history.HistoryNameException(java.lang.String) -->
<constructor name="HistoryNameException" public="true">
<parameter name="msg">
<type class="java.lang.String"/>
</parameter>
<description/>
</constructor>

</class>
</bajadoc>
