<?xml version="1.0" encoding="UTF-8"?>
<bajadoc version="2.0" createdBy="niagara-baja-doclet-1.0.9" createdAt="03-May-2024" createdOn="883e7f7a9875">
<class module="history" runtimeProfile="rt" qualifiedName="javax.baja.history.HistoryException" name="HistoryException" packageName="javax.baja.history" public="true" category="exception">
<description>
Base exception class for history.
</description>
<tag name="@author">John Sublett</tag>
<tag name="@creation">12 Jan 01</tag>
<tag name="@version">$Revision: 7$ $Date: 3/18/03 12:03:50 PM EST$</tag>
<tag name="@since">Baja 1.0</tag>
<extends>
<type class="javax.baja.sys.BajaRuntimeException"/>
</extends>
<!-- javax.baja.history.HistoryException(java.lang.String, java.lang.Throwable) -->
<constructor name="HistoryException" public="true">
<parameter name="msg">
<type class="java.lang.String"/>
</parameter>
<parameter name="e">
<type class="java.lang.Throwable"/>
</parameter>
<description>
Constructor with specified message and nested exception.
</description>
</constructor>

<!-- javax.baja.history.HistoryException(java.lang.Throwable) -->
<constructor name="HistoryException" public="true">
<parameter name="e">
<type class="java.lang.Throwable"/>
</parameter>
<description>
Constructor with specified nested exception.
</description>
</constructor>

<!-- javax.baja.history.HistoryException(java.lang.String) -->
<constructor name="HistoryException" public="true">
<parameter name="msg">
<type class="java.lang.String"/>
</parameter>
<description>
Construct a HistoryException with the given message.
</description>
</constructor>

<!-- javax.baja.history.HistoryException() -->
<constructor name="HistoryException" public="true">
<description>
No argument constructor.
</description>
</constructor>

</class>
</bajadoc>
